
"""Vector_Stores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-8XNF55qM_JVEg5i7xhKHStON_rNtp5
"""

# import os
# os.environ["GOOGLE_API_KEY"] = "see from .env"

# pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# pip install langchain-google-genai google-generativeai

# pip install -U langchain-chroma

# from langchain_google_genai import GoogleGenerativeAIEmbeddings
# from langchain_community.vectorstores import Chroma
# from langchain_core.documents import Document

# from langchain_chroma import Chroma

# doc1 = Document(
#         page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.",
#         metadata={"team": "Royal Challengers Bangalore"}
#     )
# doc2 = Document(
#         page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.",
#         metadata={"team": "Mumbai Indians"}
#     )
# doc3 = Document(
#         page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.",
#         metadata={"team": "Chennai Super Kings"}
#     )
# doc4 = Document(
#         page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.",
#         metadata={"team": "Mumbai Indians"}
#     )
# doc5 = Document(
#         page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.",
#         metadata={"team": "Chennai Super Kings"}
#     )

# docs = [doc1, doc2, doc3, doc4, doc5]

# vector_store = Chroma(
#     embedding_function= GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001"),
#     persist_directory='my_chroma_db',
#     collection_name='sample'
# )

# vector_store.add_documents(docs)

# vector_store.get(include=['embeddings','documents', 'metadatas'])

# vector_store.similarity_search(
#     query='Who among these are a bowler?',
#     k=2
# )

# updated_doc1 = Document(
#     page_content="Virat Kohli, the former captain of Royal Challengers Bangalore (RCB), is renowned for his aggressive leadership and consistent batting performances. He holds the record for the most runs in IPL history, including multiple centuries in a single season. Despite RCB not winning an IPL title under his captaincy, Kohli's passion and fitness set a benchmark for the league. His ability to chase targets and anchor innings has made him one of the most dependable players in T20 cricket.",
#     metadata={"team": "Royal Challengers Bangalore"}
# )

# vector_store.update_document(document_id='d11c87ee-7c0b-4c5a-8630-5d56d8c76dd6', document=updated_doc1)

# vector_store.get(include=['embeddings','documents', 'metadatas'])