# # -*- coding: utf-8 -*-
# """Wikipedia_Ret.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1kv7tPDn_cpq4uGiynzZaAFxkdL0JW4xh
# """

# import os
# os.environ["GOOGLE_API_KEY"] = ""

# import os
# print(os.environ.get("GOOGLE_API_KEY"))

# !pip install langchain chromadb faiss-cpu  tiktoken  langchain-community wikipedia

# !pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# !pip install langchain-google-genai google-generativeai

# !pip install -U langchain-chroma

# from langchain_community.vectorstores import Chroma
# from langchain_google_genai import GoogleGenerativeAIEmbeddings
# from langchain_core.documents import Document

# from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
# from langchain.retrievers.document_compressors import LLMChainExtractor

# # Recreate the document objects from the previous data
# docs = [
#     Document(page_content=(
#         """The Grand Canyon is one of the most visited natural wonders in the world.
#         Photosynthesis is the process by which green plants convert sunlight into energy.
#         Millions of tourists travel to see it every year. The rocks date back millions of years."""
#     ), metadata={"source": "Doc1"}),

#     Document(page_content=(
#         """In medieval Europe, castles were built primarily for defense.
#         The chlorophyll in plant cells captures sunlight during photosynthesis.
#         Knights wore armor made of metal. Siege weapons were often used to breach castle walls."""
#     ), metadata={"source": "Doc2"}),

#     Document(page_content=(
#         """Basketball was invented by Dr. James Naismith in the late 19th century.
#         It was originally played with a soccer ball and peach baskets. NBA is now a global league."""
#     ), metadata={"source": "Doc3"}),

#     Document(page_content=(
#         """The history of cinema began in the late 1800s. Silent films were the earliest form.
#         Thomas Edison was among the pioneers. Photosynthesis does not occur in animal cells.
#         Modern filmmaking involves complex CGI and sound design."""
#     ), metadata={"source": "Doc4"})
# ]

# # Create a FAISS vector store from the documents
# embedding_model = OpenAIEmbeddings()
# vectorstore = FAISS.from_documents(docs, embedding_model)

# base_retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

# # Set up the compressor using an LLM
# llm = ChatOpenAI(model="gpt-3.5-turbo")
# compressor = LLMChainExtractor.from_llm(llm)

# # Create the contextual compression retriever
# compression_retriever = ContextualCompressionRetriever(
#     base_retriever=base_retriever,
#     base_compressor=compressor
# )

# # Query the retriever
# query = "What is photosynthesis?"
# compressed_results = compression_retriever.invoke(query)

# for i, doc in enumerate(compressed_results):
#     print(f"\n--- Result {i+1} ---")
#     print(doc.page_content)

# """
# --- Result 1 ---
# Photosynthesis is the process by which green plants convert sunlight into energy.

# --- Result 2 ---
# The chlorophyll in plant cells captures sunlight during photosynthesis."""