# # -*- coding: utf-8 -*-
# """Wikipedia_Ret.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1kv7tPDn_cpq4uGiynzZaAFxkdL0JW4xh
# """

# import os
# os.environ["GOOGLE_API_KEY"] = ""

# import os
# print(os.environ.get("GOOGLE_API_KEY"))

# !pip install langchain chromadb faiss-cpu  tiktoken  langchain-community wikipedia

# !pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# !pip install langchain-google-genai google-generativeai

# !pip install -U langchain-chroma

# from langchain_community.vectorstores import Chroma
# from langchain_google_genai import GoogleGenerativeAIEmbeddings
# from langchain_core.documents import Document

# # Step 1: Your source documents
# docs = [
#     Document(page_content="LangChain makes it easy to work with LLMs."),
#     Document(page_content="LangChain is used to build LLM based applications."),
#     Document(page_content="Chroma is used to store and search document embeddings."),
#     Document(page_content="Embeddings are vector representations of text."),
#     Document(page_content="MMR helps you get diverse results when doing similarity search."),
#     Document(page_content="LangChain supports Chroma, FAISS, Pinecone, and more."),
# ]

# # Step 2: Initialize embedding model
# from langchain_community.vectorstores import FAISS

# # Initialize OpenAI embeddings
# embedding_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")
# # Step 2: Create the FAISS vector store from documents
# vectorstore = FAISS.from_documents(
#     documents=docs,
#     embedding=embedding_model
# )

# # Step 4: Convert vectorstore into a retriever
# # Enable MMR in the retriever
# retriever = vectorstore.as_retriever(
#     search_type="mmr",                   # <-- This enables MMR
#     search_kwargs={"k": 3, "lambda_mult": 0}  # k = top results, lambda_mult = relevance-diversity balance
#                                                # 1 means normal searching -->less diverse , may ignore diversity
#                                               #0 means fully diverse, may ignore relevance
# )

# query = "What is langchain?"
# results = retriever.invoke(query)

# for i, doc in enumerate(results):
#     print(f"\n--- Result {i+1} ---")
#     print(doc.page_content)