# # -*- coding: utf-8 -*-
# """Wikipedia_Ret.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1kv7tPDn_cpq4uGiynzZaAFxkdL0JW4xh
# """

# import os
# os.environ["GOOGLE_API_KEY"] = ""

# import os
# print(os.environ.get("GOOGLE_API_KEY"))

# !pip install langchain chromadb faiss-cpu  tiktoken  langchain-community wikipedia

# !pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# !pip install langchain-google-genai google-generativeai

# !pip install -U langchain-chroma

# from langchain_community.vectorstores import Chroma
# from langchain_google_genai import GoogleGenerativeAIEmbeddings
# from langchain_core.documents import Document

# from langchain.retrievers.multi_query import MultiQueryRetriever

# # Step 1: Your source documents
# all_docs = [
#     Document(page_content="Regular walking boosts heart health and can reduce symptoms of depression.", metadata={"source": "H1"}),
#     Document(page_content="Consuming leafy greens and fruits helps detox the body and improve longevity.", metadata={"source": "H2"}),
#     Document(page_content="Deep sleep is crucial for cellular repair and emotional regulation.", metadata={"source": "H3"}),
#     Document(page_content="Mindfulness and controlled breathing lower cortisol and improve mental clarity.", metadata={"source": "H4"}),
#     Document(page_content="Drinking sufficient water throughout the day helps maintain metabolism and energy.", metadata={"source": "H5"}),
#     Document(page_content="The solar energy system in modern homes helps balance electricity demand.", metadata={"source": "I1"}),
#     Document(page_content="Python balances readability with power, making it a popular system design language.", metadata={"source": "I2"}),
#     Document(page_content="Photosynthesis enables plants to produce energy by converting sunlight.", metadata={"source": "I3"}),
#     Document(page_content="The 2022 FIFA World Cup was held in Qatar and drew global energy and excitement.", metadata={"source": "I4"}),
#     Document(page_content="Black holes bend spacetime and store immense gravitational energy.", metadata={"source": "I5"}),
# ]

# # Step 2: Initialize embedding model
# from langchain_community.vectorstores import FAISS

# # Initialize OpenAI embeddings
# embedding_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")
# # Step 2: Create the FAISS vector store from documents
# vectorstore = FAISS.from_documents(
#     documents=docs,
#     embedding=embedding_model
# )

# # Initialize OpenAI embeddings
# embedding_model = OpenAIEmbeddings()

# # Create FAISS vector store
# vectorstore = FAISS.from_documents(documents=all_docs, embedding=embedding_model)

# # Create retrievers
# similarity_retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": 5})

# multiquery_retriever = MultiQueryRetriever.from_llm(
#     retriever=vectorstore.as_retriever(search_kwargs={"k": 5}),
#     llm=ChatOpenAI(model="gpt-3.5-turbo")
# )

# # Query
# query = "How to improve energy levels and maintain balance?"

# # Retrieve results
# similarity_results = similarity_retriever.invoke(query)
# multiquery_results= multiquery_retriever.invoke(query)

# for i, doc in enumerate(similarity_results):
#     print(f"\n--- Result {i+1} ---")
#     print(doc.page_content)

# print("*"*150)

# for i, doc in enumerate(multiquery_results):
#     print(f"\n--- Result {i+1} ---")
#     print(doc.page_content)

# """--- Result 1 ---
# Drinking sufficient water throughout the day helps maintain metabolism and energy.

# --- Result 2 ---
# Mindfulness and controlled breathing lower cortisol and improve mental clarity.

# --- Result 3 ---
# Regular walking boosts heart health and can reduce symptoms of depression.

# --- Result 4 ---
# Deep sleep is crucial for cellular repair and emotional regulation.

# --- Result 5 ---
# The solar energy system in modern homes helps balance electricity demand.
# ******************************************************************************************************************************************************

# --- Result 1 ---
# Drinking sufficient water throughout the day helps maintain metabolism and energy.

# --- Result 2 ---
# Mindfulness and controlled breathing lower cortisol and improve mental clarity.

# --- Result 3 ---
# Regular walking boosts heart health and can reduce symptoms of depression.

# --- Result 4 ---
# Consuming leafy greens and fruits helps detox the body and improve longevity.

# --- Result 5 ---
# Deep sleep is crucial for cellular repair and emotional regulation.
# """

