# # -*- coding: utf-8 -*-
# """Wikipedia_Ret.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1kv7tPDn_cpq4uGiynzZaAFxkdL0JW4xh
# """

# import os
# os.environ["GOOGLE_API_KEY"] = ""

# !pip install langchain chromadb faiss-cpu  tiktoken  langchain-community wikipedia

# !pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# !pip install langchain-google-genai google-generativeai

# !pip install -U langchain-chroma

# from langchain_community.vectorstores import Chroma
# from langchain_google_genai import GoogleGenerativeAIEmbeddings
# from langchain_core.documents import Document

# # Step 1: Your source documents
# documents = [
#     Document(page_content="LangChain helps developers build LLM applications easily."),
#     Document(page_content="Chroma is a vector database optimized for LLM-based search."),
#     Document(page_content="Embeddings convert text into high-dimensional vectors."),
#     Document(page_content="OpenAI provides powerful embedding models."),
# ]

# # Step 2: Initialize embedding model
# embedding_model =GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

# # Step 3: Create Chroma vector store in memory
# vectorstore = Chroma.from_documents(
#     documents=documents,
#     embedding=embedding_model,
#     collection_name="my_vector_store"
# )

# # Step 4: Convert vectorstore into a retriever
# retriever = vectorstore.as_retriever(search_kwargs={"k": 2})

# query = "What is Chroma used for?"
# results = retriever.invoke(query)

# for i, doc in enumerate(results):
#     print(f"\n--- Result {i+1} ---")
#     print(doc.page_content)