# # -*- coding: utf-8 -*-
# """Wikipedia_Ret.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1kv7tPDn_cpq4uGiynzZaAFxkdL0JW4xh
# """

# import os
# os.environ["GOOGLE_API_KEY"] = ""

# !pip install langchain chromadb faiss-cpu  tiktoken  langchain-community wikipedia

# !pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# !pip install langchain-google-genai google-generativeai

# !pip install -U langchain-chroma

# from langchain_community.retrievers import WikipediaRetriever

# # Initialize the retriever (optional: set language and top_k)
# retriever = WikipediaRetriever(top_k_results=2, lang="en")

# # Define your query
# query = "the geopolitical history of india and pakistan from the perspective of a chinese"

# # Get relevant Wikipedia documents
# docs = retriever.invoke(query)

# # Print retrieved content
# for i, doc in enumerate(docs):
#     print(f"\n--- Result {i+1} ---")
#     print(f"Content:\n{doc.page_content}...")  # truncate for display