# # -*- coding: utf-8 -*-
# """you_tube_chat_bot.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1pGWfPqXJ0-Bk-VewTC26XUV9oHz4hj0N
# """

# import os
# os.environ["OPENAI_API_KEY"] = "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"

# OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

# pip install -q youtube-transcript-api langchain-community langchain-openai \
#                faiss-cpu tiktoken python-dotenv

# pip install langchain chromadb openai tiktoken pypdf langchain_openai langchain-community

# pip install langchain-google-genai google-generativeai

# pip install -U langchain-chroma

# pip install langchain-groq

# from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_openai import OpenAIEmbeddings, ChatOpenAI
# from langchain_community.vectorstores import FAISS
# from langchain_core.prompts import PromptTemplate

# from langchain_community.vectorstores import Chroma
# from langchain_google_genai import GoogleGenerativeAIEmbeddings
# from langchain_core.documents import Document

# from langchain_openai import OpenAIEmbeddings

# from langchain_groq import ChatGroq

# from langchain_community.document_loaders import YoutubeLoader

# pip install youtube-transcript-api pytube langchain-community

# pip uninstall youtube-transcript-api -y
# pip install youtube-transcript-api==0.6.1

# pip install youtube-transcript-api browser-cookie3

# pip install yt-dlp

# import yt_dlp
# import os

# video_url = "https://www.youtube.com/watch?v=Gfr50f6ZBvo&t=179s"

# # 🔥 delete old files
# for file in os.listdir():
#     if file.endswith(".vtt"):
#         os.remove(file)

# ydl_opts = {
#     "skip_download": True,
#     "writesubtitles": True,
#     "writeautomaticsub": True,
#     "subtitleslangs": ["en"],
#     "subtitlesformat": "vtt",
#     "outtmpl": "%(id)s.%(ext)s",
# }

# with yt_dlp.YoutubeDL(ydl_opts) as ydl:
#     ydl.download([video_url])

# # find new file
# file_name = None
# for file in os.listdir():
#     if file.endswith(".vtt"):
#         file_name = file
#         break

# # convert to text
# text = []
# with open(file_name, "r", encoding="utf-8") as f:
#     for line in f:
#         if (
#             "-->" not in line
#             and line.strip()
#             and "WEBVTT" not in line
#             and "Kind:" not in line
#             and "Language:" not in line
#         ):
#             text.append(line.strip())

# final_text = " ".join(text)

# print("\n")
# print(final_text)

# splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
# chunks = splitter.create_documents([final_text])

# # print((chunks))
# print(chunks)

# embeddings = OpenAIEmbeddings(
#     model="nvidia/llama-nemotron-embed-vl-1b-v2:free",
#     openai_api_key="OPENAI_API_KEY",
#     openai_api_base="https://openrouter.ai/api/v1"
# )

# print(embeddings.openai_api_key)

# vector_store = FAISS.from_documents(chunks, embeddings)

# retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 4})

# #reriever getting query and returning output
# retriever.invoke('What is deepmind')

# llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)

# prompt = PromptTemplate(
#     template="""
#       You are a helpful assistant.
#       Answer ONLY from the provided transcript context.
#       If the context is insufficient, just say you don't know.

#       {context}
#       Question: {question}
#     """,
#     input_variables = ['context', 'question']
# )

# question          = "is the topic of nuclear fusion discussed in this video? if yes then what was discussed"
# retrieved_docs    = retriever.invoke(question)

# context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)

# final_prompt = prompt.invoke({"context": context_text, "question": question})

# answer = llm.invoke(final_prompt)
# print(answer.content)

# """## Building Chains"""

# from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
# from langchain_core.output_parsers import StrOutputParser

# def format_docs(retrieved_docs):
#   context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
#   return context_text

# parallel_chain = RunnableParallel({
#      #ret is taking question as input , returning list of docs, which is fed in function and returning the context
#     'context': retriever | RunnableLambda(format_docs),
#     'question': RunnablePassthrough()
# })

# parallel_chain.invoke('who is Demis')

# parser = StrOutputParser()

# main_chain = parallel_chain | prompt | llm | parser

# main_chain.invoke('Can you summarize the video')